# This file exists to locally test run projects in docker-compose before
# deploying them to akash. Useful for debugging if something weird is happening.

version: '3'

services:
  postgres:
    image: noahsaso/subql-postgres:v1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    image: noahsaso/subql-node-cosmos:v1.10.2-1
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      PROJECT_ZIP_URL: {{zipUrl}}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://subquery-node:3000/ready" ]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: noahsaso/subql-query:v1.5.0-1
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_started
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
