specVersion: 1.0.0
name: dao-dao-daos
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: ">=0.1.0"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  Indexes DAOs. Used to support the DAO DAO search and provide a public API for
  listing DAOs.
repository: https://github.com/DA0-DA0/subquery-indexers
schema:
  file: ./schema.graphql

network:
  chainId: juno-1
  # chainId: uni-5 # testnet

  endpoint: https://rpc-v3-archive.junonetwork.io/ # mainnet 2578099 to 4136530
  # endpoint: https://rpc-archive.junonetwork.io/ # mainnet 4136532 to current
  # endpoint: https://rpc.uni.juno.deuslabs.fi:443/ # testnet

  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: https://api.subquery.network/sq/subquery/cosmos-juno-dictionary

dataSources:
  - kind: cosmos/Runtime
    startBlock: 3642048 # mainnet v1
    # startBlock: 4136532 # mainnet second fork
    # startBlock: 1 # testnet
    # startBlock: 1 # testnet
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleInstantiate
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "instantiate_contract_with_self_admin"
        - handler: handleUpdateConfig
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "update_config"
        - handler: handleUpdateAdmin
          kind: cosmos/MessageHandler
          filter:
            type: "/cosmwasm.wasm.v1.MsgExecuteContract"
            contractCall: "accept_admin_nomination"
