version: "2.0"

services:
  postgres:
    image: noahsaso/subql-postgres:v1
    expose:
      - port: 5432
        to:
          - service: subquery-node
          - service: graphql-engine
          - service: cron
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    params:
      storage:
        data:
          mount: /var/lib/postgresql/data

  cron:
    image: ghcr.io/ovrclk/akash-postgres-restore:v0.0.4
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - BACKUP_PATH=dao-dao-subql-indexers/__project__
      # get these from s3 bucket provider
      - BACKUP_KEY=__filebase_key__
      - BACKUP_SECRET=__filebase_secret__
      - BACKUP_PASSPHRASE=__encryption_passphrase__
      - BACKUP_HOST=https://s3.filebase.com
      # every 15 minutes
      - BACKUP_SCHEDULE=*/15 * * * *
      - BACKUP_RETAIN=7 days
    depends_on:
      - service: postgres

  subquery-node:
    image: noahsaso/subql-node-cosmos-v1.9.1:v1
    expose:
      - port: 3000
        to:
          - service: graphql-engine
    depends_on:
      - service: postgres
    env:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_DATABASE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      # zip must contain dist (from npm run codegen && npm run build),
      # project.yaml, proto, and schema.graphql
      - PROJECT_ZIP_URL=__url_to_project_zip__

  graphql-engine:
    image: noahsaso/subql-query-v1.5.0:v1
    expose:
      - port: 3000
        to:
          - global: true
    depends_on:
      - service: postgres
      - service: subquery-node
    env:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_DATABASE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432

profiles:
  compute:
    postgres:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: data
            size: 5Gi
            attributes:
              persistent: true
              class: beta2
    cron:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    subquery-node:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    graphql-engine:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    akash:
      # audited by akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        postgres:
          denom: uakt
          amount: 500
        cron:
          denom: uakt
          amount: 500
        subquery-node:
          denom: uakt
          amount: 500
        graphql-engine:
          denom: uakt
          amount: 500

deployment:
  postgres:
    akash:
      profile: postgres
      count: 1
  cron:
    akash:
      profile: cron
      count: 1
  subquery-node:
    akash:
      profile: subquery-node
      count: 1
  graphql-engine:
    akash:
      profile: graphql-engine
      count: 2
